### ISSUE TITLE
Can you add a sound when a certain name on friend's list logs in?

### ISSUE THREAD

**Issue by CoinsRS** [wtommyw/pm-highlight#2]
I'm looking for a plugin that will make a sound when someone specific on my friend's list logs in so that I can be notified and follow-up with them on a request they had for me before. Your plugin that I found is the closest to what I am looking for. Would it be possible for you to add the option of enabling sound notifications via RuneLite for this?

**Comment by wtommyw** [comment]
Sounds doable, I'll have a look at the docs and maybe start this week if I get to it.

**Comment by wtommyw** [comment]
I have added login notifications, you'll be able to use the new checkbox soon.

![image](https://puu.sh/Jmfbi/319ce4593f.png)

I have also added a default option, this setting will be used when adding new friends to your highlights.

![image](https://puu.sh/JmfbH/a3108d0134.png)

The only downside is that notifications are only sent when the client is out of focus, this is out of my control.

**Comment by wtommyw** [comment]
The update will be available as soon runelite decides to merge it, you can see the status [here](https://github.com/runelite/plugin-hub/pull/3352).

**Comment by CoinsRS** [comment]
Hey mate, this is wonderful, thanks so much! I'll let others know about it in the bulks community as often times we get referrals to follow-up on for anyone that expressed interest in a collection, and this combined with adding notes on a player is perfect.

Also the notifications when the client is out of focus is not a big deal, a workaround is going to the RuneLite settings directly and enabling "Send notifications when focused" and that will allow the plugins to send notifications to you as if your client was out of focus on the computer.
