### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by AardPlugs** [wtommyw/pm-highlight#4]
i can't tell if any other plugins should interupt it, or something else... but it wont work no matter what am doing ??

**Comment by wtommyw** [comment]
Hey, what part doesn't work? If you want friends' names to be highlighted you'll have to set your private to `show all`.

Coloured messaged still work when private is set to `friends`.

This is a problem with the way that names are coloured, I'm still looking for a way to fix this but I've not been able to find it yet.

**Comment by AardPlugs** [comment]
i got everything "On" private And so on, but none of the Pm's change color at all

**Comment by wtommyw** [comment]
Strange, I've just tested it in game and it seems to be working.

Could you send a screenshot of your settings so that I can have a look? You can simply drag and drop the image in the text box here.

**Comment by AardPlugs** [comment]
Which settings exactly  would you like ?

**Comment by wtommyw** [comment]
The plugins sidepanel should be enough, something like this:

![](https://puu.sh/JyqvP/736705c911.png)

The games' normal chat settings shouldn't affect the plugin

**Comment by wtommyw** [comment]
I'm closing your issue as it has been inactive for a month. I assume you've either found a solution or moved on.

Feel free to reopen this issue with additional information if your problem has not been solved.
